on:
  release:
    types: [created]

name: Build & release
jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v4

    # build the binaries
    - uses: wangyoucao577/go-release-action@v1.40
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: "portal"
        pre_command: export CGO_ENABLED=0
        project_path: "./portal"
        asset_name: portal-${{ matrix.goos }}-${{ matrix.goarch }}
        md5sum: false
        overwrite: true
        retry: 5
        ldflags: -w -X "TAG=${{ steps.meta.outputs.tags }}"
        compress_assets: "OFF"
